name: bnotes
description: Note taking application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+16

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_breakpoints: ^0.1.1
  animations: ^2.0.2

  bitsdojo_window: ^0.1.1+1

  cupertino_icons: ^1.0.4

  file_picker: ^4.3.3
  flex_color_scheme: ^5.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_markdown: ^0.6.9
  flutter_phoenix: ^1.0.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_widget_from_html: ^0.8.0
  
  iconsax: ^0.0.8
  intl: ^0.17.0

  line_icons: ^2.0.1
  local_auth: ^2.1.0

  nextcloud: ^3.0.2

  package_info_plus: ^1.3.0
  path_provider: ^2.0.9
  
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  side_navigation: ^1.0.2
  sqflite: ^2.0.2

  uuid: ^3.0.5
  url_launcher: ^6.0.20
  universal_platform: ^1.0.0+1
  
  yaru_icons: ^0.2.1

flutter_icons:
  # android: "launcher_icon"
  ios: true
  image_path: "images/bnotes-transparent.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
      - asset: res/Raleway-Regular.ttf
      - asset: res/Raleway-Light.ttf

  assets:
    - images/bnotes.png
    - images/bnotes-transparent.png
    - images/google.png